services:
  # Build the app
  app:
    build: .
    image: nextjs
    ports:
      - 3000:3000
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST}
    depends_on:
      - database
