import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "@/lib/utils";
import { QueryProvider } from "@/lib/query-provider";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Plain-IO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={cn(GeistSans.className)}>
          <QueryProvider>{children}</QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
